http_port 80

auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/htpasswd
auth_param basic realm proxy
auth_param basic credentialsttl 1 minute

acl authenticated proxy_auth REQUIRED

http_access allow authenticated
http_access deny all
